site_name: LayoutDocs
extra_css: [css/extra.css]
extra_javascript: [js/color_blocks.js]
theme:
    name: material
    #     features:
    #   - search.highlight <--- in the future
    palette:
        scheme: slate
markdown_extensions:
    - admonition
    - toc: # https://python-markdown.github.io/extensions/toc/
          permalink: True
          toc_depth: 4
    - md_in_html
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
nav:
  - Home: index.md
  - Definitions: definitions.md
  - Global Guide:
      - 1. Getting Started: guide/1-getting-started.md
      - 2. Firmware Files: guide/2-firmware-files.md
      - 3. Filetypes: guide/3-filetypes.md
      - 4. Diffing: 
          - What is Diffing?:  guide/4-diffpatch/index.md
          - Diffpatching: guide/4-diffpatch/diff-example.md
      - 5. Menu Files:
        - Introduction: guide/5-menu-docs/index.md
        - Menus:
            - Common: guide/5-menu-docs/menus/common/index.md
            - Home Menu: guide/5-menu-docs/menus/ResidentMenu/index.md
            - Lockscreen: guide/5-menu-docs/menus/Entrance/index.md
            - All Apps: guide/5-menu-docs/menus/Flaunch/index.md
            #     - Settings: guide/5-menu-docs/menus/Set/index.md
            - Player Select: guide/5-menu-docs/menus/Psl/index.md
            #     - User Page: guide/5-menu-docs/MyPage/index.md
            #     - News: guide/5-menu-docs/Notification/index.md
      - 6. Layouts:
          - Getting Started: guide/6-layouts/index.md
          - USD Sections: guide/6-layouts/usd-sections.md
      - 7. Animations:
          - Introduction: guide/7-animations/index.md
          - "Quick refresher course: Nintendo Switch files, diffing": guide/7-animations/refresher.md
          - Main tutorial: guide/7-animations/main-tutorial.md
          - Animation templates: guide/7-animations/anim-templates.md
          - More on animations: guide/7-animations/going-further.md
          - "PaiTags and Targets": guide/7-animations/paitags-and-targets.md
          - "szs, bflyt, bflan files": guide/7-animations/szs-bflyt-bflan.md
      - 8. Custom Messages/Text: guide/8-messages/index.md
      - 9. Manual szs theming (unsupported applets): guide/9-manualszs/index.md
  - Specific Guides:
      - Getting Started: examples/index.md
      #     Changing Component Sizes: examples/changing-component-sizes/index.md
      #     Repositioning the Gamerow: examples/reposition-gamerow/index.md
      - Stationary Game Icons: examples/stationary-game-icons/index.md
      - Custom Element Colors: examples/custom-element-colors/index.md
      - Custom Applet Icons: examples/custom-applet-icons/index.md
      - Custom Cursor: examples/custom-cursor/index.md
      - Hide Footer Line: examples/hide-footer-line/index.md
      - Hide Header Lines: examples/hide-header-lines/index.md
      #     Changing Applet Cursor Size: examples/changing-applet-cursor-size/index.md
      - Pulling & Pushing Panes: examples/pull-push-front-back/index.md
      - Disabling Hud Movement: examples/disabling-clock-movement-caused-by-battery/index.md
  - Extras:
      - Guides: extras/guides.md
      - Tools: extras/tools.md
      - Discord Servers: extras/discord-servers.md
      - Other: extras/other.md
